"""Rendering the comparison page — R16.

**Generated mechanically from `results/`, never hand-edited.** A hand-maintained table drifts
from the documents it claims to summarise, and the drift always favours whoever maintains it
(P68 — a published figure needs a mechanical relation to its source).

**It is not a ranking, and the ordering says so.** Rows are sorted by scanner name, never by
performance. R10 forbids a composite score precisely because it invites rank-ordering, and a
page that sorted by "best" would reintroduce through layout exactly what the document format
refuses to contain. poison-garden is a registrar; registrars publish registers, not
league tables.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from poison_garden.scoring.score import MIN_SPECIMENS_FOR_A_CLAIM

GENERATED_MARKER = "<!-- GENERATED BY `poison-garden leaderboard` — DO NOT EDIT BY HAND -->"


def _load(results_dir: Path) -> list[dict[str, Any]]:
    out = []
    for path in sorted(results_dir.glob("*.json")):
        try:
            payload = json.loads(path.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            continue
        if isinstance(payload, dict) and "per_class" in payload:
            payload["_file"] = path.name
            out.append(payload)
    return out


INSUFFICIENT_MARK = "†"


def _cell(entry: dict[str, Any]) -> str:
    """One class cell — `caught/total`, marked when the class is too small to quote (R19).

    The table never printed percentages, which is why this defect survived review: `1/1` is
    literally accurate. But a reader skimming a row does the division, and `1/1` reads as
    100% with none of the warning a bare "100%" would carry. The mark is what stops a cell
    from being quoted as a property of the scanner when it is a property of one specimen.

    `sufficient_n` is recomputed from `total` when absent rather than defaulted to True.
    Documents submitted before R19 existed have no such key, and treating a missing flag as
    "sufficient" would leave exactly the old, unmarked cells unmarked — the guard would then
    be newest-document-only, which is the population that needs it least.
    """
    caught, total = entry["caught"], entry["total"]
    sufficient = entry.get("sufficient_n", total >= MIN_SPECIMENS_FOR_A_CLAIM)
    return f"{caught}/{total}" + ("" if sufficient else f" {INSUFFICIENT_MARK}")


def render(results_dir: str | Path) -> str:
    """Build the comparison page from committed result documents."""
    documents = _load(Path(results_dir))

    lines = [
        GENERATED_MARKER,
        "",
        "# Scanner comparison",
        "",
        "Generated from the result documents committed in [`results/`](results/). Every",
        "figure below was produced by the vendor running `poison-garden run` themselves.",
        "**poison-garden does not run anyone's scanner and does not compute anyone's score.**",
        "",
        "**This is not a ranking.** Rows are ordered by scanner name. There is no composite",
        "score to sort by, deliberately — an aggregate hides the one class where a tool did",
        "badly, which is usually the interesting one. Compare the columns you care about.",
        "",
    ]

    if not documents:
        lines += [
            "_No results submitted yet._",
            "",
            "To add one, run the corpus against your scanner and open a pull request with the",
            "result document. See [`results/README.md`](results/README.md).",
            "",
        ]
        return "\n".join(lines) + "\n"

    classes = sorted({e["class"] for d in documents for e in d.get("per_class", [])})

    header = ["Scanner", "Corpus", *classes, "False positives"]
    lines.append("| " + " | ".join(header) + " |")
    lines.append("|" + "|".join(["---"] * len(header)) + "|")

    # Sorted by scanner name. Never by any figure.
    for doc in sorted(documents, key=lambda d: str(d.get("scanner", {}).get("name", ""))):
        per_class = {e["class"]: e for e in doc.get("per_class", [])}
        corpus = doc.get("corpus", {})
        fp = doc.get("false_positives", {})

        row = [
            str(doc.get("scanner", {}).get("name", "?")),
            f"{corpus.get('version', '?')}",
        ]
        for klass in classes:
            entry = per_class.get(klass)
            row.append("—" if entry is None else _cell(entry))
        row.append(f"{len(fp.get('specimens', []))}/{fp.get('benign_total', 0)}")
        lines.append("| " + " | ".join(row) + " |")

    lines += [
        "",
        "## Reading this table",
        "",
        "- A cell is `caught/total` for that attack class. A dash means the submission",
        "  predates that class existing in the corpus.",
        f"- **A `{INSUFFICIENT_MARK}` means that class holds fewer than "
        f"{MIN_SPECIMENS_FOR_A_CLAIM} scorable specimens** and the cell is not evidence",
        "  about the scanner. At one specimen the 95% interval on the true rate runs from",
        "  0% to 79% either way — `0/1` is not a gap and `1/1` is not coverage. Each result",
        "  document carries the full interval per class in `recall_ci95`.",
        "- **Specimens that errored are excluded from both numerator and denominator.** A",
        "  specimen a scanner could not be asked about is a defect in this corpus, not a",
        "  finding about that tool.",
        "- **False positives are over the benign twins**, which are specimens deliberately",
        "  built to look tempting. Any scanner reaches 100% recall by flagging everything;",
        "  this column is what makes that visible.",
        "- Rows citing different corpus versions are not directly comparable. The corpus",
        "  hash each result describes is recorded in its own document.",
        "",
    ]
    return "\n".join(lines) + "\n"


def write(results_dir: str | Path, out_path: str | Path) -> Path:
    target = Path(out_path)
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(render(results_dir), encoding="utf-8")
    return target


def is_stale(results_dir: str | Path, out_path: str | Path) -> bool:
    """True if the committed page does not match what the results would render.

    CI asserts this is False, so a hand-edit — or a merged result whose page was never
    regenerated — fails rather than silently publishing a table that disagrees with the
    documents beneath it.
    """
    target = Path(out_path)
    if not target.is_file():
        return True
    return target.read_text(encoding="utf-8") != render(results_dir)
